// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(SmServisContext))]
    [Migration("20230418074018_mig_67")]
    partial class mig67
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.AnaSektor", b =>
                {
                    b.Property<int>("AnaSektorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnaSektorId"));

                    b.Property<string>("AnaSektorAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnaSektorId");

                    b.ToTable("AnaSektors");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AnaSektor_BagliSektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnaSektorId")
                        .HasColumnType("integer");

                    b.Property<int>("BagliSektorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnaSektorId");

                    b.HasIndex("BagliSektorId");

                    b.ToTable("AnaSektor_BagliSektors");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BagliSektor", b =>
                {
                    b.Property<int>("BagliSektorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BagliSektorId"));

                    b.Property<int>("AnaSektorId")
                        .HasColumnType("integer");

                    b.Property<string>("BagliSektorAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BagliSektorId");

                    b.HasIndex("AnaSektorId");

                    b.ToTable("BagliSektors");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CalismaDurumu", b =>
                {
                    b.Property<int>("CalismaDurumuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalismaDurumuId"));

                    b.Property<string>("CalismaDurumuAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CalismaDurumuId");

                    b.ToTable("CalismaDurumus");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Cari", b =>
                {
                    b.Property<int>("CariId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AnaSektorId")
                        .HasColumnType("integer");

                    b.Property<int?>("BagliSektorId")
                        .HasColumnType("integer");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariDil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariDurumId")
                        .HasColumnType("integer");

                    b.Property<int>("CariTipiId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaNo")
                        .HasColumnType("integer");

                    b.Property<string>("HesapKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IlceId")
                        .HasColumnType("integer");

                    b.Property<string>("MailAdresi1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailAdresi2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParaBirimiId")
                        .HasColumnType("integer");

                    b.Property<int>("SehirId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("integer");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebSitesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("eFaturaMukellefi")
                        .HasColumnType("boolean");

                    b.Property<bool>("eIrsaliyeMukellefi")
                        .HasColumnType("boolean");

                    b.HasKey("CariId");

                    b.HasIndex("AnaSektorId");

                    b.HasIndex("BagliSektorId");

                    b.HasIndex("CariDurumId");

                    b.HasIndex("CariTipiId");

                    b.HasIndex("IlceId");

                    b.HasIndex("ParaBirimiId");

                    b.HasIndex("SehirId");

                    b.HasIndex("UlkeId");

                    b.ToTable("Caris");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CariDurum", b =>
                {
                    b.Property<int>("CariDurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariDurumId"));

                    b.Property<string>("CariDurumAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CariDurumId");

                    b.ToTable("CariDurums");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CariPersonel", b =>
                {
                    b.Property<int>("CariPersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariPersonelId"));

                    b.Property<string>("Adres1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres2")
                        .HasColumnType("text");

                    b.Property<int>("CalismaDurumuId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<string>("CariPersonelAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelAdi2")
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("integer");

                    b.Property<bool>("SerivsMailGonder")
                        .HasColumnType("boolean");

                    b.Property<bool>("ServisFaturaGonder")
                        .HasColumnType("boolean");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Silinecek")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnvanId")
                        .HasColumnType("integer");

                    b.HasKey("CariPersonelId");

                    b.HasIndex("CalismaDurumuId");

                    b.HasIndex("CariId");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("UnvanId");

                    b.ToTable("CariPersonels");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CariTipi", b =>
                {
                    b.Property<int>("CariTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariTipiId"));

                    b.Property<string>("CariTipiAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CariTipiId");

                    b.ToTable("CariTipis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Cinsiyet", b =>
                {
                    b.Property<int>("CinsiyetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CinsiyetId"));

                    b.Property<string>("CinsiyetAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CinsiyetId");

                    b.ToTable("Cinsiyets");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Departman", b =>
                {
                    b.Property<int>("DepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmanId"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmanId");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.FaturalamaPeriyodu", b =>
                {
                    b.Property<int>("FaturalamaPeriyoduId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FaturalamaPeriyoduId"));

                    b.Property<string>("FaturalamaPeriyoduAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriyotNo")
                        .HasColumnType("integer");

                    b.Property<int>("PeriyotSayisi")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FaturalamaPeriyoduId");

                    b.ToTable("FaturalamaPeriyodus");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IlceId"));

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("text");

                    b.Property<int>("SehirId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IlceId");

                    b.HasIndex("SehirId");

                    b.ToTable("Ilces");
                });

            modelBuilder.Entity("EntityLayer.Concrete.IlgiliKisiler", b =>
                {
                    b.Property<int>("IlgiliKisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IlgiliKisiId"));

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IlgiliKisiId");

                    b.ToTable("IlgiliKisilers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.IslemYeri", b =>
                {
                    b.Property<int>("IslemYeriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IslemYeriId"));

                    b.Property<string>("IslemYeriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IslemYeriId");

                    b.ToTable("IslemYeris");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Modul", b =>
                {
                    b.Property<int>("ModulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModulId"));

                    b.Property<string>("ModulAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModulKisaltma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModulNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ModulId");

                    b.ToTable("Moduls");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Modul_ServisDepartman", b =>
                {
                    b.Property<int>("Modul_ServisDepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Modul_ServisDepartmanId"));

                    b.Property<int>("ModulId")
                        .HasColumnType("integer");

                    b.Property<int>("ServisDepartmanId")
                        .HasColumnType("integer");

                    b.HasKey("Modul_ServisDepartmanId");

                    b.HasIndex("ModulId");

                    b.ToTable("Modul_ServisDepartmans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Oncelik", b =>
                {
                    b.Property<int>("OncelikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OncelikId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OncelikAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OncelikId");

                    b.ToTable("Onceliks");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ParaBirimi", b =>
                {
                    b.Property<int>("ParaBirimiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParaBirimiId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParaBirimiAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimiKisaltma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimiSimge")
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParaBirimiId");

                    b.ToTable("ParaBirimis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Adres1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres2")
                        .HasColumnType("text");

                    b.Property<bool>("CalismaDurumu")
                        .HasColumnType("boolean");

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonelAdi2")
                        .HasColumnType("text");

                    b.Property<string>("PersonelKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonelKullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("PersonelSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnvanId")
                        .HasColumnType("integer");

                    b.HasKey("PersonelId");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("UnvanId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PersonelTipi", b =>
                {
                    b.Property<int>("PersonelTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelTipiId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonelTipiAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PersonelTipiId");

                    b.ToTable("PersonelTipis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Pozisyon", b =>
                {
                    b.Property<int>("PozisyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PozisyonId"));

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PozisyonAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PozisyonId");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Pozisyons");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Proje", b =>
                {
                    b.Property<int>("ProjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjeId"));

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjeId");

                    b.HasIndex("CariId");

                    b.ToTable("Projes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ProjeIcerik", b =>
                {
                    b.Property<int>("ProjeIcerikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjeIcerikId"));

                    b.Property<string>("Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GecerlilikTarihBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GecerlilikTarihBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParaBirimiId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonelTipiId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjeIcerikId");

                    b.HasIndex("ParaBirimiId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PersonelTipiId");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeIceriks");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SehirId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlakaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefonKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("integer");

                    b.HasKey("SehirId");

                    b.HasIndex("UlkeId");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisBilgi", b =>
                {
                    b.Property<int>("ServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServisId"));

                    b.Property<string>("Ay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmanYetkilisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FTSuresi")
                        .HasColumnType("text");

                    b.Property<string>("GercekSure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GirilenSure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Kapandi")
                        .HasColumnType("boolean");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModulId")
                        .HasColumnType("integer");

                    b.Property<bool>("MusteriOnayi")
                        .HasColumnType("boolean");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OncelikId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlanlananTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServisDepartmanId")
                        .HasColumnType("integer");

                    b.Property<string>("ServisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServisSekliId")
                        .HasColumnType("integer");

                    b.Property<int>("ServisTipiId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SonDurumID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDurumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TSuresi")
                        .HasColumnType("text");

                    b.Property<string>("TahminiSure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Yil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServisId");

                    b.HasIndex("CariId");

                    b.HasIndex("ModulId");

                    b.HasIndex("OncelikId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("ServisDepartmanId");

                    b.HasIndex("ServisTipiId");

                    b.HasIndex("SonDurumID");

                    b.ToTable("ServisBilgis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisDepartman", b =>
                {
                    b.Property<int>("ServisDepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServisDepartmanId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServisDepartmanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServisDepartmanId");

                    b.ToTable("ServisDepartmans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisKalem", b =>
                {
                    b.Property<int>("KalemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KalemId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslamaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenelAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IslemYeriId")
                        .HasColumnType("integer");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServisBilgiServisId")
                        .HasColumnType("integer");

                    b.Property<int>("ServisId")
                        .HasColumnType("integer");

                    b.Property<string>("ServisKalemNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<int>("SonDurumId")
                        .HasColumnType("integer");

                    b.Property<string>("Sure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KalemId");

                    b.HasIndex("ServisBilgiServisId");

                    b.ToTable("ServisKalems");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisSekli", b =>
                {
                    b.Property<int>("ServisSekliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServisSekliId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServisSekliAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServisSekliId");

                    b.ToTable("ServisSeklis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisTipi", b =>
                {
                    b.Property<int>("ServisTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServisTipiId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServisTipiAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServisTipiId");

                    b.ToTable("ServisTipis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SonDurum", b =>
                {
                    b.Property<int>("SonDurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SonDurumId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SonDurumAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SonDurumId");

                    b.ToTable("SonDurums");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Sube", b =>
                {
                    b.Property<int>("SubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubeId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubeId");

                    b.ToTable("Subes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempCari", b =>
                {
                    b.Property<int>("CariId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AnaSektorId")
                        .HasColumnType("integer");

                    b.Property<int?>("BagliSektorId")
                        .HasColumnType("integer");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariDil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariDurumId")
                        .HasColumnType("integer");

                    b.Property<int>("CariTipiId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaNo")
                        .HasColumnType("integer");

                    b.Property<string>("HesapKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IlceId")
                        .HasColumnType("integer");

                    b.Property<string>("MailAdresi1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailAdresi2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParaBirimiId")
                        .HasColumnType("integer");

                    b.Property<int>("SehirId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UlkeId")
                        .HasColumnType("integer");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebSitesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("eFaturaMukellefi")
                        .HasColumnType("boolean");

                    b.Property<bool>("eIrsaliyeMukellefi")
                        .HasColumnType("boolean");

                    b.HasKey("CariId");

                    b.HasIndex("AnaSektorId");

                    b.HasIndex("BagliSektorId");

                    b.HasIndex("CariDurumId");

                    b.HasIndex("CariTipiId");

                    b.HasIndex("IlceId");

                    b.HasIndex("ParaBirimiId");

                    b.HasIndex("SehirId");

                    b.HasIndex("UlkeId");

                    b.ToTable("TempCaris");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempCariPersonel", b =>
                {
                    b.Property<int>("CariPersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CariPersonelId"));

                    b.Property<string>("Adres1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres2")
                        .HasColumnType("text");

                    b.Property<int>("CalismaDurumuId")
                        .HasColumnType("integer");

                    b.Property<string>("CariPersonelAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelAdi2")
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariPersonelSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("integer");

                    b.Property<bool>("SerivsMailGonder")
                        .HasColumnType("boolean");

                    b.Property<bool>("ServisFaturaGonder")
                        .HasColumnType("boolean");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnvanId")
                        .HasColumnType("integer");

                    b.HasKey("CariPersonelId");

                    b.HasIndex("CalismaDurumuId");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("UnvanId");

                    b.ToTable("TempCariPersonels");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempDanisman", b =>
                {
                    b.Property<int>("TempDanismanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TempDanismanId"));

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelTipiId")
                        .HasColumnType("integer");

                    b.HasKey("TempDanismanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PersonelTipiId");

                    b.ToTable("TempDanismans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempServisBilgi", b =>
                {
                    b.Property<int>("TempServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TempServisId"));

                    b.Property<string>("Ay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmanYetkilisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FTSuresi")
                        .HasColumnType("text");

                    b.Property<string>("GercekSure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GirilenSure")
                        .HasColumnType("text");

                    b.Property<bool>("Kapandi")
                        .HasColumnType("boolean");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModulId")
                        .HasColumnType("integer");

                    b.Property<bool>("MusteriOnayi")
                        .HasColumnType("boolean");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<int>("OncelikId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlanlananTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServisDepartmanId")
                        .HasColumnType("integer");

                    b.Property<string>("ServisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServisSekliId")
                        .HasColumnType("integer");

                    b.Property<int>("ServisTipiId")
                        .HasColumnType("integer");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<int>("SonDurumID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDurumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TSuresi")
                        .HasColumnType("text");

                    b.Property<string>("TahminiSure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Yil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TempServisId");

                    b.HasIndex("CariId");

                    b.HasIndex("ModulId");

                    b.HasIndex("OncelikId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("ServisDepartmanId");

                    b.HasIndex("ServisTipiId");

                    b.HasIndex("SonDurumID");

                    b.ToTable("TempServisBilgis");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempServisKalem", b =>
                {
                    b.Property<int>("TempKalemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TempKalemId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslamaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenelAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IslemYeriId")
                        .HasColumnType("integer");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("ServisKalemNo")
                        .HasColumnType("text");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<int>("SonDurumId")
                        .HasColumnType("integer");

                    b.Property<string>("Sure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TempKalemId");

                    b.ToTable("TempServisKalems");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Ulke", b =>
                {
                    b.Property<int>("UlkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UlkeId"));

                    b.Property<string>("BinaryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefonKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TripleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UlkeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UlkeId");

                    b.ToTable("Ulkes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Unvan", b =>
                {
                    b.Property<int>("UnvanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnvanId"));

                    b.Property<int>("Olusturan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SonDegistiren")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonDegistirmeTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnvanAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnvanKisaltma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UnvanId");

                    b.ToTable("Unvans");
                });

            modelBuilder.Entity("EntityLayer.Concrete.AnaSektor_BagliSektor", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AnaSektor", "AnaSektor")
                        .WithMany()
                        .HasForeignKey("AnaSektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.BagliSektor", "BagliSektor")
                        .WithMany()
                        .HasForeignKey("BagliSektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaSektor");

                    b.Navigation("BagliSektor");
                });

            modelBuilder.Entity("EntityLayer.Concrete.BagliSektor", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AnaSektor", "AnaSektor")
                        .WithMany()
                        .HasForeignKey("AnaSektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaSektor");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Cari", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AnaSektor", "AnaSektor")
                        .WithMany()
                        .HasForeignKey("AnaSektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.BagliSektor", "BagliSektor")
                        .WithMany()
                        .HasForeignKey("BagliSektorId");

                    b.HasOne("EntityLayer.Concrete.CariDurum", "CariDurum")
                        .WithMany()
                        .HasForeignKey("CariDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.CariTipi", "CariTipi")
                        .WithMany()
                        .HasForeignKey("CariTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ParaBirimi", "ParaBirimi")
                        .WithMany()
                        .HasForeignKey("ParaBirimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaSektor");

                    b.Navigation("BagliSektor");

                    b.Navigation("CariDurum");

                    b.Navigation("CariTipi");

                    b.Navigation("Ilce");

                    b.Navigation("ParaBirimi");

                    b.Navigation("Sehir");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CariPersonel", b =>
                {
                    b.HasOne("EntityLayer.Concrete.CalismaDurumu", "CalismaDurumu")
                        .WithMany()
                        .HasForeignKey("CalismaDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Pozisyon", "Pozisyon")
                        .WithMany()
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalismaDurumu");

                    b.Navigation("Cari");

                    b.Navigation("Cinsiyet");

                    b.Navigation("Departman");

                    b.Navigation("Pozisyon");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Ilce", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Modul_ServisDepartman", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modul");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Personel", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Pozisyon", "Pozisyon")
                        .WithMany()
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinsiyet");

                    b.Navigation("Departman");

                    b.Navigation("Pozisyon");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Pozisyon", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Proje", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ProjeIcerik", b =>
                {
                    b.HasOne("EntityLayer.Concrete.ParaBirimi", "ParaBirimi")
                        .WithMany()
                        .HasForeignKey("ParaBirimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.HasOne("EntityLayer.Concrete.PersonelTipi", "PersonelTipi")
                        .WithMany()
                        .HasForeignKey("PersonelTipiId");

                    b.HasOne("EntityLayer.Concrete.Proje", "Proje")
                        .WithMany()
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParaBirimi");

                    b.Navigation("Personel");

                    b.Navigation("PersonelTipi");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Sehir", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisBilgi", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Oncelik", "Oncelik")
                        .WithMany()
                        .HasForeignKey("OncelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ServisDepartman", "ServisDepartman")
                        .WithMany()
                        .HasForeignKey("ServisDepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ServisTipi", "ServisTipi")
                        .WithMany()
                        .HasForeignKey("ServisTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.SonDurum", "SonDurum")
                        .WithMany()
                        .HasForeignKey("SonDurumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Modul");

                    b.Navigation("Oncelik");

                    b.Navigation("Personel");

                    b.Navigation("ServisDepartman");

                    b.Navigation("ServisTipi");

                    b.Navigation("SonDurum");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ServisKalem", b =>
                {
                    b.HasOne("EntityLayer.Concrete.ServisBilgi", "ServisBilgi")
                        .WithMany()
                        .HasForeignKey("ServisBilgiServisId");

                    b.Navigation("ServisBilgi");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempCari", b =>
                {
                    b.HasOne("EntityLayer.Concrete.AnaSektor", "AnaSektor")
                        .WithMany()
                        .HasForeignKey("AnaSektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.BagliSektor", "BagliSektor")
                        .WithMany()
                        .HasForeignKey("BagliSektorId");

                    b.HasOne("EntityLayer.Concrete.CariDurum", "CariDurum")
                        .WithMany()
                        .HasForeignKey("CariDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.CariTipi", "CariTipi")
                        .WithMany()
                        .HasForeignKey("CariTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ParaBirimi", "ParaBirimi")
                        .WithMany()
                        .HasForeignKey("ParaBirimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaSektor");

                    b.Navigation("BagliSektor");

                    b.Navigation("CariDurum");

                    b.Navigation("CariTipi");

                    b.Navigation("Ilce");

                    b.Navigation("ParaBirimi");

                    b.Navigation("Sehir");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempCariPersonel", b =>
                {
                    b.HasOne("EntityLayer.Concrete.CalismaDurumu", "CalismaDurumu")
                        .WithMany()
                        .HasForeignKey("CalismaDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Pozisyon", "Pozisyon")
                        .WithMany()
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalismaDurumu");

                    b.Navigation("Cinsiyet");

                    b.Navigation("Departman");

                    b.Navigation("Pozisyon");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempDanisman", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.PersonelTipi", "PersonelTipi")
                        .WithMany()
                        .HasForeignKey("PersonelTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("PersonelTipi");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TempServisBilgi", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Oncelik", "Oncelik")
                        .WithMany()
                        .HasForeignKey("OncelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ServisDepartman", "ServisDepartman")
                        .WithMany()
                        .HasForeignKey("ServisDepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ServisTipi", "ServisTipi")
                        .WithMany()
                        .HasForeignKey("ServisTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.SonDurum", "SonDurum")
                        .WithMany()
                        .HasForeignKey("SonDurumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Modul");

                    b.Navigation("Oncelik");

                    b.Navigation("Personel");

                    b.Navigation("ServisDepartman");

                    b.Navigation("ServisTipi");

                    b.Navigation("SonDurum");
                });
#pragma warning restore 612, 618
        }
    }
}
